import DashContContainer from "@/components/gui/DashContContainer";
import styled from "styled-components";

const ParagraphBlock = styled.p`
  margin-top: 1rem;
  margin-bottom: 1rem;
  font-family: Arial, sans-serif;
  line-height: 1.5;
  font-size: 1.2rem;
  letter-spacing: 0.5px;
`;

export function TabAboutPage() {
  return (
    <DashContContainer title="About" disableValidation={true}>
      <ParagraphBlock>
        This is an amateur tool to visualize G-code files for 3D printing.
      </ParagraphBlock>
      <ParagraphBlock>
        As a former owner of a Ender 3 printer, I has several technical issues
        with it that motivated me to create this tool to try to better
        understand and visualize the G-code generated by the slicer for 3D
        printing.
      </ParagraphBlock>
      <ParagraphBlock>
        Only tested with Ultimaker Cura 5.x outputing Marlin flavor G-code.
        Other slicers or G-code flavors may not be fully supported. Looking
        forward to add multiple parser support in the future.
      </ParagraphBlock>
    </DashContContainer>
  );
}
